site_name: Markdown Dreams

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets:
      base_path: 'snippets/'

nav:
    - 'How to do things with Markdown': 'index.md'
    - 'Getting started': 'getting-started/getting-started.md'
    - 'Tools':
        - 'Markdown editors': 'tools/tools-editors.md'
        - 'Storage': 'tools/tools-storage.md'
        - 'Git': 
            - 'About Git': 'tools/tools-git.md'
            - 'Git setup': 'tools/tools-git-setup.md'
            - 'Git basics': 'tools/tools-git-basics.md'
        - 'Publishing': 'tools/tools-publishing.md'
    - 'Recipes':
#        - 'Overview': 'recipes/index.md'
        - 'Take notes': 'recipes/recipes-notes.md'
        - 'Edit a Git wiki': 'recipes/recipes-git-wiki.md'
        - 'Collaborate using Git centralized workflow': 'recipes/recipes-centralized-workflow.md'
        - 'Manage docs with GitHub Flow': 'recipes/recipes-gitflow.md'
        - 'Publish a website with Hugo': 'recipes/recipes-hugo.md'
        - 'Publish documentation with MkDocs': 'recipes/recipes-mkdocs.md'
        - 'Create a Word document': 'recipes/recipes-pandoc-word.md'
        - 'Create an eBook': 'recipes/recipes-pandoc-ebook.md'
        - 'Create a PDF': 'recipes/recipes-pandoc-pdf.md'
        - 'Grab a web page': 'recipes/recipes-pandoc-web.md'
        - 'Create a Powerpoint presentation': 'recipes/recipes-slides.md'
        - 'Create a DZSlides presentation': 'recipes/recipes-slides-dzslides.md'
        - 'Create a Remark presentation': 'recipes/recipes-slides-remark.md'
    - 'Resources': 
        - 'Markdown cheatsheet': 'resources/markdown-cheatsheet.md'
        - 'Glossary': 'resources/resources-glossary.md'
        - 'Templates': 'resources/templates.md'
        - 'Links': 'resources/links.md'

